import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { lstat, readdir, readFile, stat } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

/** @typedef {{ name: string, platforms: string[] }} SkillJson */
/** @typedef {{ refCount: number, exampleCount: number }} ValidationSummary */

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SKILL = join(ROOT, "source/skills/webcpu-easel");
const GENERATED = join(ROOT, ".build/generated");
const DIST = join(ROOT, "dist");
const MODE = process.argv.includes("--package") ? "package" : "source-clean";
const execFileAsync = promisify(execFile);
const GENERATED_AGENT_HEADER =
	"<!-- Generated by scripts/generate-agent-surfaces.mjs from AGENTS.md. Do not edit directly. -->";
const REQUIRED_REFERENCES = [
	"api-index.md",
	"class-signatures.md",
	"enums-constants.md",
	"version-provenance.md",
	"package-identity.md",
	"module-imports.md",
	"deno-runtime.md",
	"type-inspection-guide.md",
	"setup.md",
	"core-concepts.md",
	"renderer-framebuffer.md",
	"render-pipeline.md",
	"cpu-rasterizer-constraints.md",
	"lifecycle-disposal.md",
	"cameras-controls.md",
	"geometry-builtins.md",
	"geometry-manual.md",
	"materials.md",
	"lights-fog.md",
	"textures-assets.md",
	"render-loop-recipes.md",
	"input-picking.md",
	"animation.md",
	"voxel-worlds.md",
	"sprites-lines-points.md",
	"loaders-serialization.md",
	"performance.md",
	"threejs-migration.md",
	"createjs-easeljs-comparison.md",
	"webgl-webgpu-comparison.md",
	"renderer-orchestration.md",
	"chunked-voxel-terrain.md",
	"texture-atlas-pipeline.md",
	"hierarchical-voxel-rigging.md",
	"pointer-input-and-grid-picking.md",
];
const REQUIRED_AGENT_FILES = [
	"AGENTS.md",
	"CLAUDE.md",
	"GEMINI.md",
	"llms.txt",
	"llms-full.txt",
	".github/copilot-instructions.md",
	".cursor/rules/webcpu-easel.mdc",
	".rules",
	".aiassistant/rules/webcpu-easel.md",
	".junie/AGENTS.md",
	".clinerules/00-webcpu-easel.md",
	".roo/rules/00-webcpu-easel.md",
	".augment/rules/webcpu-easel.md",
	"docs/agent-platforms.md",
];
const GENERATED_AGENT_FILES = REQUIRED_AGENT_FILES.filter(
	(file) => file !== "AGENTS.md" && !file.startsWith("llms"),
);
const GENERATED_SKILLS = [
	"claude/skills/webcpu-easel/SKILL.md",
	"codex/plugin/webcpu-agent-skill/skills/webcpu-easel/SKILL.md",
	"opencode/templates/skills/webcpu-easel/SKILL.md",
	"copilot/templates/.github/skills/webcpu-easel/SKILL.md",
	"copilot/templates/.copilot/skills/webcpu-easel/SKILL.md",
];
const TYPE_IMPORT_PREFIX_RE = /^type\s+/;
const EXPORT_ALIAS_RE = /\s+as\s+.*/;
const DUPLICATED_SHARED_ASSET_RE = /(^|\/)(reference|examples|templates)\//;
const BODY_REFERENCE_LINK_RE = /`(reference\/[^`]+\.md)`/g;
const IMPORTED_EASEL_SYMBOL_RE =
	/import(?:\s+type)?\s+\{([^}]+)\} from "@xsyetopz\/easel"/g;
const API_SYMBOL_RE = /- `([^`]+)`/g;
const LLMS_LINK_RE = /^- \[([^\]]+)\]\(([^)]+)\):/gm;
const LLMS_LINE_LINK_RE = /^- \[([^\]]+)\]\(([^)]+)\):/;
const URL_SCHEME_RE = /^[a-z]+:/i;
const LLMS_OPTIONAL_HEADING_RE = /^## Optional$/m;
const LLMS_H2_RE = /^## .+/m;
const FORBIDDEN_SOURCE_TEXT_PATTERNS = [
	["fun", "times"].join(""),
	["/Users/", "krystian"].join(""),
	["Code", "Projects"].join(""),
	["Local source", " basis"].join(""),
	["biome", "-ignore"].join(""),
];
const SOURCE_TEXT_EXTENSIONS = new Set([
	".html",
	".json",
	".md",
	".mdc",
	".mjs",
	".rules",
	".ts",
	".tsx",
	".txt",
]);
const TEMPLATES = [
	"vite-vanilla-ts",
	"react-canvas",
	"astro-canvas",
	"voxel-world-starter",
	"deno-browser",
];
const DENO_REQUIRED_TEXT = [
	"deno.json",
	"npm:",
	"jsr:",
	"HTMLCanvasElement",
	"deno check",
	"exactOptionalPropertyTypes",
	"RenderableScene",
	"renderScene",
];
const COPIED_CONTRIBUTING_TERMS = [
	"Musi",
	"grammar/",
	"crates/",
	"vscode-ext",
	"music_syntax",
];
const PACKAGED_SKILL_DIRS = [
	"claude/skills/webcpu-easel",
	"codex/plugin/webcpu-agent-skill/skills/webcpu-easel",
	"opencode/templates/skills/webcpu-easel",
	"copilot/templates/.github/skills/webcpu-easel",
	"copilot/templates/.copilot/skills/webcpu-easel",
];

/** @param {string} path @returns {Promise<string>} */
async function read(path) {
	return await readFile(path, "utf8");
}

/** @param {string} dir @returns {Promise<string[]>} */
async function walk(dir) {
	const entries = await readdir(dir, { withFileTypes: true });
	const files = [];
	for (const entry of entries) {
		const path = join(dir, entry.name);
		if (entry.name === "node_modules") continue;
		if (entry.isDirectory()) files.push(...(await walk(path)));
		else if (entry.isFile()) files.push(path);
	}
	return files;
}

/** @param {string} rootPath @returns {Promise<string[]>} */
async function filesForRoot(rootPath) {
	const entry = await lstat(rootPath);
	return entry.isDirectory() ? await walk(rootPath) : [rootPath];
}

/** @param {unknown} condition @param {string} message @returns {asserts condition} */
function assert(condition, message) {
	if (!condition) throw new Error(message);
}

/** @param {string} apiText @returns {Set<string>} */
function parseApiSymbols(apiText) {
	const symbols = new Set();
	for (const match of apiText.matchAll(API_SYMBOL_RE)) {
		const symbol = match[1];
		if (symbol) symbols.add(symbol);
	}
	return symbols;
}

/** @param {string} text @returns {Set<string>} */
function importedSymbols(text) {
	const symbols = new Set();
	for (const match of text.matchAll(IMPORTED_EASEL_SYMBOL_RE)) {
		const imports = match[1];
		if (!imports) continue;
		for (const raw of imports.split(",")) {
			const name = raw
				.trim()
				.replace(TYPE_IMPORT_PREFIX_RE, "")
				.replace(EXPORT_ALIAS_RE, "");
			if (name) symbols.add(name);
		}
	}
	return symbols;
}

/** @param {string} path @returns {boolean} */
function isTextSource(path) {
	return SOURCE_TEXT_EXTENSIONS.has(path.slice(path.lastIndexOf(".")));
}

async function validateNoForbiddenSourceText() {
	for (const root of [
		"scripts",
		"source",
		"README.md",
		"CONTRIBUTING.md",
		"CODE_OF_CONDUCT.md",
		"AGENTS.md",
		"CLAUDE.md",
		"llms.txt",
		"llms-full.txt",
		"GEMINI.md",
		".github",
		".cursor",
		".rules",
		".aiassistant",
		".junie",
		".clinerules",
		".roo",
		".augment",
		"docs",
	]) {
		const rootPath = join(ROOT, root);
		const files = await filesForRoot(rootPath);
		for (const file of files) {
			if (!isTextSource(file)) continue;
			const text = await read(file);
			assert(
				!FORBIDDEN_SOURCE_TEXT_PATTERNS.some((pattern) =>
					text.toLowerCase().includes(pattern.toLowerCase()),
				),
				`forbidden local/provenance text in ${relative(ROOT, file)}`,
			);
		}
	}
}

/** @param {string} href @returns {boolean} */
function isLocalHref(href) {
	return !(URL_SCHEME_RE.test(href) || href.startsWith("#"));
}

/** @param {string} href @returns {string} */
function linkPath(href) {
	return href.split("#")[0] ?? "";
}

/** @param {string} path @returns {Promise<void>} */
async function validateLlmsManifest(path) {
	const text = await read(join(ROOT, path));
	assert(text.startsWith("# "), `${path} must start with H1`);
	assert(
		text.split("\n").some((line) => line.startsWith("> ")),
		`${path} must include blockquote summary`,
	);
	assert(LLMS_OPTIONAL_HEADING_RE.test(text), `${path} missing ## Optional`);
	assert(LLMS_H2_RE.test(text), `${path} must include H2 sections`);
	const links = [...text.matchAll(LLMS_LINK_RE)];
	assert(links.length > 0, `${path} must include markdown links`);
	let optional = false;
	for (const line of text.split("\n")) {
		if (line.startsWith("## ")) optional = line === "## Optional";
		const match = line.match(LLMS_LINE_LINK_RE);
		if (!match || optional) continue;
		const href = match[2];
		if (!(href && isLocalHref(href))) continue;
		const target = linkPath(href);
		assert(target, `${path} has empty link target`);
		assert(
			existsSync(join(ROOT, target)),
			`${path} missing linked file ${target}`,
		);
	}
}

async function validateLlmsSurfaces() {
	await validateLlmsManifest("llms.txt");
	await validateLlmsManifest("llms-full.txt");
}

async function validateAgentInstructionSurfaces() {
	for (const file of REQUIRED_AGENT_FILES) {
		assert(
			existsSync(join(ROOT, file)),
			`missing agent instruction file ${file}`,
		);
	}
	const claudeStat = await lstat(join(ROOT, "CLAUDE.md"));
	assert(!claudeStat.isSymbolicLink(), "CLAUDE.md must be a real file");
	for (const file of GENERATED_AGENT_FILES) {
		const text = await read(join(ROOT, file));
		assert(
			text.includes(GENERATED_AGENT_HEADER),
			`generated agent file missing header ${file}`,
		);
	}
	const claude = await read(join(ROOT, "CLAUDE.md"));
	const gemini = await read(join(ROOT, "GEMINI.md"));
	const agents = await read(join(ROOT, "AGENTS.md"));
	const llms = await read(join(ROOT, "llms.txt"));
	const llmsFull = await read(join(ROOT, "llms-full.txt"));
	assert(claude.includes("@AGENTS.md"), "CLAUDE.md must import AGENTS.md");
	assert(gemini.includes("@./AGENTS.md"), "GEMINI.md must import AGENTS.md");
	for (const file of [
		".rules",
		".github/copilot-instructions.md",
		".clinerules/00-webcpu-easel.md",
	]) {
		const text = await read(join(ROOT, file));
		assert(
			text.includes("# WebCPU EASEL.js Agent Instructions"),
			`${file} must materialize AGENTS.md instructions`,
		);
	}
	for (const text of [agents, llms, llmsFull]) {
		assert(
			text.includes("@xsyetopz/easel") && text.includes("UNKNOWN"),
			"agent instruction surfaces must include package baseline and UNKNOWN rule",
		);
	}
	await execFileAsync(process.execPath, [
		join(ROOT, "scripts/generate-agent-surfaces.mjs"),
		"--check",
	]);
}

function validateNoTemplateNodeModules() {
	for (const template of TEMPLATES) {
		assert(
			!existsSync(join(SKILL, "templates", template, "node_modules")),
			`template ${template} must not contain node_modules`,
		);
	}
}

async function validateDenoSupport() {
	const denoDoc = await read(join(SKILL, "reference/deno-runtime.md"));
	const moduleDoc = await read(join(SKILL, "reference/module-imports.md"));
	for (const text of DENO_REQUIRED_TEXT) {
		assert(
			denoDoc.includes(text) || moduleDoc.includes(text),
			`Deno documentation missing ${text}`,
		);
	}
	const denoJson = join(SKILL, "templates/deno-browser/deno.json");
	const denoMain = join(SKILL, "templates/deno-browser/src/main.ts");
	const denoHtml = join(SKILL, "templates/deno-browser/index.html");
	assert(existsSync(denoJson), "missing Deno template deno.json");
	assert(existsSync(denoMain), "missing Deno template src/main.ts");
	assert(existsSync(denoHtml), "missing Deno template index.html");
	const config = JSON.parse(await read(denoJson));
	assert(
		config.imports?.["@xsyetopz/easel"] === "jsr:@xsyetopz/easel@0.4.5",
		"Deno template must pin @xsyetopz/easel import",
	);
	const denoMainText = await read(denoMain);
	for (const text of [
		"RenderableScene",
		"renderScene",
		"scene.fog !== undefined",
	]) {
		assert(denoMainText.includes(text), `Deno template missing ${text}`);
	}
}

async function validateNoRootDuplication() {
	for (const root of ["claude", "codex", "opencode", "copilot", ".agents"]) {
		const rootPath = join(ROOT, root);
		if (!existsSync(rootPath)) continue;
		for (const file of await walk(rootPath)) {
			const normalized = relative(ROOT, file).replaceAll("\\", "/");
			assert(
				!(
					DUPLICATED_SHARED_ASSET_RE.test(normalized) ||
					normalized.endsWith("/REFERENCE.md")
				),
				`duplicated shared skill asset outside source/build/dist: ${normalized}`,
			);
		}
	}
}

function validateSourceCleanMode() {
	for (const generated of [".build", "dist", ".agents"]) {
		assert(
			!existsSync(join(ROOT, generated)),
			`${generated} exists; run bun run clean before source-clean validation`,
		);
	}
}

/** @param {string} root @returns {Promise<void>} */
async function validateClaudeMarketplace(root) {
	const pluginPath = join(root, "claude/.claude-plugin/plugin.json");
	const marketplacePath = join(root, "claude/.claude-plugin/marketplace.json");
	assert(
		existsSync(pluginPath),
		`missing Claude plugin manifest ${pluginPath}`,
	);
	assert(
		existsSync(marketplacePath),
		`missing Claude marketplace manifest ${marketplacePath}`,
	);
	const plugin = JSON.parse(await read(pluginPath));
	const marketplace = JSON.parse(await read(marketplacePath));
	assert(plugin.name === "webcpu-agent-skill", "Claude plugin name mismatch");
	assert(
		marketplace.name === "webcpu-agent-skill",
		"Claude marketplace name mismatch",
	);
	assert(
		marketplace.owner?.name === "xsyetopz",
		"Claude marketplace owner mismatch",
	);
	assert(
		Array.isArray(marketplace.plugins) && marketplace.plugins.length === 1,
		"Claude marketplace must list one plugin",
	);
	const [entry] = marketplace.plugins;
	assert(entry.name === plugin.name, "Claude marketplace plugin name mismatch");
	assert(
		entry.version === plugin.version,
		"Claude marketplace version mismatch",
	);
	assert(entry.source === "./", "Claude marketplace source must be ./");
}

async function validateContributing() {
	const text = await read(join(ROOT, "CONTRIBUTING.md"));
	for (const term of COPIED_CONTRIBUTING_TERMS) {
		assert(
			!text.includes(term),
			`CONTRIBUTING.md copied term remains: ${term}`,
		);
	}
	for (const required of [
		"webcpu-agent-skill",
		"bun run check",
		"bun run generate:agents",
		"bun run validate:source",
		"@xsyetopz/easel@0.4.5",
	]) {
		assert(text.includes(required), `CONTRIBUTING.md missing ${required}`);
	}
}

async function validateGenerated() {
	for (const file of GENERATED_SKILLS) {
		assert(existsSync(join(GENERATED, file)), `missing generated ${file}`);
		const text = await read(join(GENERATED, file));
		assert(text.startsWith("---\n"), `missing frontmatter ${file}`);
		assert(text.includes("# WebCPU EASEL.js"), `missing skill body ${file}`);
	}
	for (const plugin of [
		"claude/.claude-plugin/plugin.json",
		"claude/.claude-plugin/marketplace.json",
		"codex/plugin/webcpu-agent-skill/.codex-plugin/plugin.json",
	]) {
		assert(
			existsSync(join(GENERATED, plugin)),
			`missing generated plugin ${plugin}`,
		);
		JSON.parse(await read(join(GENERATED, plugin)));
	}
	await validateClaudeMarketplace(GENERATED);
}

async function validatePackageMode() {
	await validateGenerated();
	await validateClaudeMarketplace(DIST);
	for (const dir of PACKAGED_SKILL_DIRS) {
		const full = join(DIST, dir);
		assert(existsSync(join(full, "SKILL.md")), `missing packaged skill ${dir}`);
		for (const child of [
			"REFERENCE.md",
			"reference",
			"examples",
			"templates",
		]) {
			assert(existsSync(join(full, child)), `missing packaged ${dir}/${child}`);
		}
	}
	assert(
		existsSync(join(DIST, ".agents/plugins/marketplace.json")),
		"missing dist marketplace",
	);
	for (const file of REQUIRED_AGENT_FILES) {
		assert(existsSync(join(DIST, file)), `missing packaged ${file}`);
	}
	for (const file of ["llms/llms-ctx.txt", "llms/llms-ctx-full.txt"]) {
		assert(existsSync(join(DIST, file)), `missing packaged ${file}`);
	}
	for (const file of ["CONTRIBUTING.md", "CODE_OF_CONDUCT.md"]) {
		assert(existsSync(join(DIST, file)), `missing packaged ${file}`);
	}
}

/** @returns {Promise<ValidationSummary>} */
async function validateSourceContent() {
	/** @type {SkillJson} */
	const meta = JSON.parse(await read(join(SKILL, "skill.json")));
	assert(meta.name === "webcpu-easel", "skill.json name mismatch");
	assert(meta.platforms.length === 4, "skill.json must target 4 platforms");
	for (const ref of REQUIRED_REFERENCES) {
		assert(
			existsSync(join(SKILL, "reference", ref)),
			`missing reference/${ref}`,
		);
	}
	await validateNoForbiddenSourceText();
	await validateAgentInstructionSurfaces();
	await validateContributing();
	await validateLlmsSurfaces();
	validateNoTemplateNodeModules();
	await validateDenoSupport();
	await validateNoRootDuplication();
	const body = await read(join(SKILL, "body.md"));
	for (const match of body.matchAll(BODY_REFERENCE_LINK_RE)) {
		const refPath = match[1];
		assert(refPath, "empty body reference link");
		assert(existsSync(join(SKILL, refPath)), `body links missing ${refPath}`);
	}
	const apiText = await read(join(SKILL, "reference/api-index.md"));
	assert(
		apiText.includes("@xsyetopz/easel@0.4.5"),
		"api-index missing baseline version",
	);
	const symbols = parseApiSymbols(apiText);
	for (const required of [
		"Renderer",
		"Scene",
		"PerspectiveCamera",
		"Geometry",
		"BasicMaterial",
		"DataTexture",
		"Raycaster",
	]) {
		assert(symbols.has(required), `api-index missing ${required}`);
	}
	const exampleFiles = await walk(join(SKILL, "examples"));
	assert(exampleFiles.length >= 12, "expected at least 12 examples");
	for (const file of exampleFiles) {
		const text = await read(file);
		assert(
			text.includes("@xsyetopz/easel"),
			`example missing package import ${relative(ROOT, file)}`,
		);
		for (const symbol of importedSymbols(text)) {
			assert(
				symbols.has(symbol),
				`example imports unknown symbol ${symbol} in ${relative(ROOT, file)}`,
			);
		}
	}
	for (const template of TEMPLATES) {
		if (template === "deno-browser") continue;
		const pkgPath = join(SKILL, "templates", template, "package.json");
		assert(existsSync(pkgPath), `missing template package ${template}`);
		const pkg = JSON.parse(await read(pkgPath));
		assert(
			pkg.dependencies?.["@xsyetopz/easel"] === "0.4.5",
			`template ${template} must pin easel 0.4.5`,
		);
	}
	const refFiles = await walk(join(SKILL, "reference"));
	for (const file of refFiles) {
		const st = await stat(file);
		assert(st.size > 80, `reference too small ${relative(ROOT, file)}`);
	}
	return { refCount: refFiles.length, exampleCount: exampleFiles.length };
}

async function validate() {
	const result = await validateSourceContent();
	if (MODE === "source-clean") validateSourceCleanMode();
	else await validatePackageMode();
	console.log(
		`Validation passed (${MODE}): ${result.refCount} source references, ${result.exampleCount} examples.`,
	);
}

validate().catch((error) => {
	console.error(error.message);
	process.exitCode = 1;
});
